//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neddle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Courses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Courses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neddle.Resources.Courses", typeof(Courses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course having id {0} could not be deleted. See the application log for more information..
        /// </summary>
        internal static string CourseCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("CourseCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to delete course having id {0}..
        /// </summary>
        internal static string CourseDelete {
            get {
                return ResourceManager.GetString("CourseDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Course having id {0} does not exist..
        /// </summary>
        internal static string CourseDoesNotExist {
            get {
                return ResourceManager.GetString("CourseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to locate course having id {0}..
        /// </summary>
        internal static string CourseExists {
            get {
                return ResourceManager.GetString("CourseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course having id {0} does exists {1}..
        /// </summary>
        internal static string CourseExistsResult {
            get {
                return ResourceManager.GetString("CourseExistsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to load course having id {0}..
        /// </summary>
        internal static string CourseLoad {
            get {
                return ResourceManager.GetString("CourseLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseManger was initialized with provider of type {0}..
        /// </summary>
        internal static string CourseManagerStartup {
            get {
                return ResourceManager.GetString("CourseManagerStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to save course having id {0}..
        /// </summary>
        internal static string CourseSave {
            get {
                return ResourceManager.GetString("CourseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to update course having id {0}..
        /// </summary>
        internal static string CourseUpdate {
            get {
                return ResourceManager.GetString("CourseUpdate", resourceCulture);
            }
        }
    }
}
